#!/bin/bash
echo "🎰 Deploying fixed roulette engine..."
echo ""
echo "📋 Manual Deployment Instructions:"
echo ""
echo "1. Go to Supabase Dashboard → Edge Functions"
echo "2. Find 'roulette-engine' function"
echo "3. Click 'Edit' or 'Update'"
echo "4. Replace the entire code with the content from:"
echo "   supabase/functions/roulette-engine/index.ts"
echo ""
echo "5. Key changes to verify:"
echo "   - Line 713-717: Should call atomic_bet_balance_check with:"
echo "     p_user_id: userId,"
echo "     p_bet_amount: betAmount,"
echo "     p_round_id: roundId"
echo ""
echo "6. Click 'Deploy' or 'Save'"
echo ""
echo "🔄 After deployment:"
echo "1. Wait 30-60 seconds for function to fully deploy"
echo "2. Try placing a roulette bet"
echo "3. Check browser console for any new errors"
echo ""
echo "📊 If still getting schema cache errors:"
echo "1. Go to SQL Editor in Supabase Dashboard"
echo "2. Run: SELECT pg_reload_conf();"
echo "3. Wait 10 seconds, then try betting again"
echo ""
echo "✅ Expected result: Instant balance deduction when bet is placed!"