name: Deploy Supabase Edge Functions

on:
  push:
    branches:
      - main
    paths:
      - 'supabase/functions/**'
  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest
          
      - name: Deploy roulette-engine function
        run: supabase functions deploy roulette-engine --project-ref $SUPABASE_PROJECT_ID
        
      - name: Deploy coinflip-streak-engine function  
        run: supabase functions deploy coinflip-streak-engine --project-ref $SUPABASE_PROJECT_ID
        
      - name: Deploy crash-engine function
        run: supabase functions deploy crash-engine --project-ref $SUPABASE_PROJECT_ID
        
      - name: Deploy tower-engine function
        run: supabase functions deploy tower-engine --project-ref $SUPABASE_PROJECT_ID
        
      - name: Deploy case-opening-engine function
        run: supabase functions deploy case-opening-engine --project-ref $SUPABASE_PROJECT_ID
        
      - name: Deploy claim-free-case function
        run: supabase functions deploy claim-free-case --project-ref $SUPABASE_PROJECT_ID